<?php

namespace BiblioBundle\Repository;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCollections(){
        $gb = $this -> createQueryBuilder('l');
        $gb -> select('l.titre','l.auteur')->groupBy('l.titre');
        return $gb->getQuery()->getResult();
    }
}
